# Generated by Django 5.1 on 2024-09-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0003_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
